### ISSUE TITLE
session-endpoint attribute not observed

### ISSUE THREAD

**Issue by paulerickson** [myuw-web-components/myuw-profile#15]
I'm trying to use this in an AngularJS app, so the attributes are initially placeholders and then interpolated after initialization.  Because session-endpoint is not observed or handled outside of the connect handler, it can never transition out of the session-less state ("LOGIN").

It would be nice to have some kind of refresh function or event handler, too.

**Comment by thevoiceofzeke** [comment]
Hey Paul,

As you have likely already discovered (#24), the API has changed to better accommodate session changes (#20). Specifically, it now listens for a custom event to tell it when a session exists, explained in the readme here: https://github.com/myuw-web-components/myuw-profile#displaying-the-component

Hopefully this has resolved the issue!

**Comment by paulerickson** [comment]
thanks, that works for me!
