### ISSUE TITLE
Profile dropdown missing background on Firefox

### ISSUE THREAD

**Issue by ChristianMurphy** [myuw-web-components/myuw-profile#18]
![screenshot_2018-10-03 https myuw-web-components github io](https://user-images.githubusercontent.com/3107513/46434668-1f62c580-c709-11e8-8c06-336d88a98d79.png)

Tested on FireFox 62.0 64-bit Ubuntu

**Comment by davidmsibley** [comment]
I think this would be fixed by the addition of css-vars-ponyfill: https://github.com/myuw-web-components/myuw-profile/commit/65aec922ad3ce740dc74179ab699058c7f61c2db

Care to test again?

**Comment by ChristianMurphy** [comment]
Retested with Firefox 63 and latest version
![screenshot_2018-11-07 https myuw-web-components github io](https://user-images.githubusercontent.com/3107513/48157637-6ce4cc00-e28d-11e8-836a-49f4fb3314fc.png)
![screenshot_2018-11-07 https myuw-web-components github io 1](https://user-images.githubusercontent.com/3107513/48157638-6d7d6280-e28d-11e8-93af-e9a8bc0bdaaa.png)
Looks good now :+1: 

Thanks @davidmsibley !
